# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8943221b625e4fde1ed2440225623c05bb6b8a727a2516a7f7334a717cfac7523b7f79d3aae2c1ed36216062c0f81e652d369355c827e039e5879c4ec06b6612

test:
  secret_key_base: f02f74ac4e8bbe105313c04f37289c0d8002b5005ec2ebe977aa637870e8985ee3950ceae9d4979ad206576b69e520ecb70bd4550397c242935e7bcff0fd36c4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
